import { describe, expect, it } from "vitest";
import { normalizePublishContract } from "@/lib/registry-publish-contract";
import { sha256Utf8 } from "@/lib/cozy-provenance";

describe("normalizePublishContract", () => {
  it("create: does not merge stub-inferred deps unless applyStubInference is true", () => {
    const files = {
      "index.tsx": `// auto-generated by cozy registry. do not edit.
export * from "./_deps/alice/button/index";`,
    };
    const withoutOptIn = normalizePublishContract({
      mode: "create",
      input: { registryDependencies: ["@alice/theme"] },
      files,
    });
    expect(withoutOptIn.ok).toBe(true);
    if (!withoutOptIn.ok) return;
    expect(withoutOptIn.value.registryDependenciesToWrite?.sort()).toEqual(
      ["@alice/theme"].sort(),
    );
    expect(withoutOptIn.value.diagnostics.stubInferredRegistryDependencies.sort()).toEqual(
      ["@alice/button"].sort(),
    );
    expect(withoutOptIn.value.diagnostics.stubInferenceMergedIntoWrite).toBe(false);

    const withOptIn = normalizePublishContract({
      mode: "create",
      input: {
        registryDependencies: ["@alice/theme"],
        applyStubInference: true,
      },
      files,
    });
    expect(withOptIn.ok).toBe(true);
    if (!withOptIn.ok) return;
    expect(withOptIn.value.registryDependenciesToWrite?.sort()).toEqual(
      ["@alice/button", "@alice/theme"].sort(),
    );
    expect(withOptIn.value.diagnostics.stubInferenceMergedIntoWrite).toBe(true);
  });

  it("version: absent field yields undefined write (inherit)", () => {
    const r = normalizePublishContract({
      mode: "version",
      input: {},
      files: { "index.tsx": "export default function(){}" },
    });
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value.registryDependenciesToWrite).toBeUndefined();
  });

  it("version: explicit empty array clears", () => {
    const r = normalizePublishContract({
      mode: "version",
      input: { registryDependencies: [] },
      files: { "index.tsx": "export default function(){}" },
    });
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value.registryDependenciesToWrite).toEqual([]);
  });

  it("version + provenance: merges previous deps when field absent", () => {
    const r = normalizePublishContract({
      mode: "version",
      input: {
        provenance: {
          schemaVersion: 1,
          root: { ref: "@alice/dialog" },
          files: [
            { path: "index.tsx", source: "root" },
            {
              path: "Button.tsx",
              source: "registry",
              ref: "@alice/button@1.0.0",
            },
          ],
        },
      },
      files: {
        "index.tsx": "export {}",
        "Button.tsx": "export {}",
      },
      previousRegistryDependencies: ["@alice/old"],
    });
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    const deps = r.value.registryDependenciesToWrite?.slice().sort() ?? [];
    expect(deps).toContain("@alice/old");
    expect(deps).toContain("@alice/button@1.0.0");
  });

  it("strict: dirty registry file fails with PROV_DIRTY_DEPENDENCY", () => {
    const content = "CHANGED";
    const r = normalizePublishContract({
      mode: "create",
      input: {
        provenancePolicy: "strict",
        provenance: {
          schemaVersion: 1,
          root: { ref: "@alice/x" },
          files: [
            { path: "index.tsx", source: "root" },
            {
              path: "Vendor.tsx",
              source: "registry",
              ref: "@alice/v@1.0.0",
              contentHash: sha256Utf8("ORIGINAL"),
            },
          ],
        },
      },
      files: {
        "index.tsx": "export {}",
        "Vendor.tsx": content,
      },
    });
    expect(r.ok).toBe(false);
    if (r.ok) return;
    expect(r.code).toBe("PROV_DIRTY_DEPENDENCY");
  });

  it("split: dirty registry file fails with PROV_SPLIT_NOT_IMPLEMENTED", () => {
    const r = normalizePublishContract({
      mode: "create",
      input: {
        provenancePolicy: "split",
        provenance: {
          schemaVersion: 1,
          root: { ref: "@alice/x" },
          files: [
            { path: "index.tsx", source: "root" },
            {
              path: "Vendor.tsx",
              source: "registry",
              ref: "@alice/v@1.0.0",
              contentHash: sha256Utf8("ORIGINAL"),
            },
          ],
        },
      },
      files: {
        "index.tsx": "export {}",
        "Vendor.tsx": "CHANGED",
      },
    });
    expect(r.ok).toBe(false);
    if (r.ok) return;
    expect(r.code).toBe("PROV_SPLIT_NOT_IMPLEMENTED");
  });

  it("inlineVendor: keeps vendor file content instead of stub", () => {
    const vendorBody = "export const V = 1;";
    const r = normalizePublishContract({
      mode: "create",
      input: {
        provenancePolicy: "inlineVendor",
        provenance: {
          schemaVersion: 1,
          root: { ref: "@alice/x" },
          files: [
            { path: "index.tsx", source: "root" },
            {
              path: "Vendor.tsx",
              source: "registry",
              ref: "@alice/v@1.0.0",
            },
          ],
        },
      },
      files: {
        "index.tsx": "export {}",
        "Vendor.tsx": vendorBody,
      },
    });
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value.filesToWrite?.["Vendor.tsx"]).toBe(vendorBody);
  });
});
