import { describe, expect, it } from "vitest";

import { collectExplicitRegistryImportRefs } from "@/lib/registry-source-dependencies";

describe("collectExplicitRegistryImportRefs", () => {
  it("collects project-scoped Cozy refs from Cozy-generated stubs", () => {
    const refs = collectExplicitRegistryImportRefs({
      "index.tsx": `
        // auto-generated by cozy registry. do not edit.
        export { Button } from "@indeed-cozy/ds/button";
        export { Card } from "@indeed-cozy/dashboard/card@1.2.0";
      `,
    });

    expect(refs).toEqual([
      "@indeed-cozy/dashboard/card@1.2.0",
      "@indeed-cozy/ds/button",
    ]);
  });

  it("ignores ordinary npm scoped packages", () => {
    const refs = collectExplicitRegistryImportRefs({
      "index.tsx": `
        // auto-generated by cozy registry. do not edit.
        import { Slot } from "@radix-ui/react-slot";
        import { Dialog } from "@base-ui/react/dialog";
      `,
    });

    expect(refs).toEqual([]);
  });

  it("does not infer refs from normal user-authored source files", () => {
    const refs = collectExplicitRegistryImportRefs({
      "index.tsx": `
        export { Button } from "@indeed-cozy/ds/button";
      `,
    });

    expect(refs).toEqual([]);
  });
});
