import { parseRegistryDependencyRef } from "@/lib/registry-graph";

const COZY_STUB_MARKER = "auto-generated by cozy registry";
const COZY_STUB_EXPORT_RE = /export\s+(?:\*|\{[^}]*\})\s+from\s+["']([^"']+)["']/g;

export function collectExplicitRegistryImportRefs(
  files: Record<string, string>,
): string[] {
  const refs = new Set<string>();

  for (const source of Object.values(files)) {
    if (!source.includes(COZY_STUB_MARKER)) continue;
    let match: RegExpExecArray | null;
    while ((match = COZY_STUB_EXPORT_RE.exec(source)) !== null) {
      const specifier = match[1];
      const parsed = parseRegistryDependencyRef(specifier);
      if (!parsed?.project) continue;
      refs.add(
        `@${parsed.owner}/${parsed.project}/${parsed.name}${parsed.version ? `@${parsed.version}` : ""}`,
      );
    }
  }

  return Array.from(refs).sort();
}

export function mergeRegistryDependencyRefs(
  ...groups: Array<readonly string[] | null | undefined>
): string[] {
  const merged = new Set<string>();
  for (const group of groups) {
    for (const ref of group ?? []) {
      const trimmed = typeof ref === "string" ? ref.trim() : "";
      if (trimmed) merged.add(trimmed);
    }
  }
  return Array.from(merged).sort();
}
