export const RUNTIME_PROVIDED_DEPENDENCIES = [
  "react",
  "react-dom",
  "react-dom/client",
  "react/jsx-runtime",
] as const;

export const TRUSTED_BUILT_IN_DEPENDENCIES = [
  "lucide-react",
  "clsx",
  "class-variance-authority",
  "tailwind-merge",
  "@base-ui/react",
  "@hugeicons/react",
  "@hugeicons/core-free-icons",
] as const;

export const TRUSTED_BUILT_IN_NAMESPACE_PREFIXES = [
  "@base-ui/",
  "@hugeicons/",
  "@radix-ui/",
] as const;

export const BLOCKED_THIRD_PARTY_DEPENDENCIES = [
  "@aws-sdk/client-s3",
  "@prisma/client",
  "better-sqlite3",
  "bcrypt",
  "canvas",
  "child_process",
  "fsevents",
  "fs",
  "mongodb",
  "next",
  "node-gyp",
  "path",
  "pg-native",
  "sharp",
  "sqlite3",
] as const;

const NODE_BUILTIN_MODULE_NAMES = [
  "_http_agent",
  "_http_client",
  "_http_common",
  "_http_incoming",
  "_http_outgoing",
  "_http_server",
  "_stream_duplex",
  "_stream_passthrough",
  "_stream_readable",
  "_stream_transform",
  "_stream_wrap",
  "_stream_writable",
  "_tls_common",
  "_tls_wrap",
  "assert",
  "assert/strict",
  "async_hooks",
  "buffer",
  "child_process",
  "cluster",
  "console",
  "constants",
  "crypto",
  "dgram",
  "diagnostics_channel",
  "dns",
  "dns/promises",
  "domain",
  "events",
  "fs",
  "fs/promises",
  "http",
  "http2",
  "https",
  "inspector",
  "inspector/promises",
  "module",
  "net",
  "os",
  "path",
  "path/posix",
  "path/win32",
  "perf_hooks",
  "process",
  "punycode",
  "querystring",
  "readline",
  "readline/promises",
  "repl",
  "stream",
  "stream/consumers",
  "stream/promises",
  "stream/web",
  "string_decoder",
  "sys",
  "timers",
  "timers/promises",
  "tls",
  "trace_events",
  "tty",
  "url",
  "util",
  "util/types",
  "v8",
  "vm",
  "wasi",
  "worker_threads",
  "zlib",
] as const;

export const NODE_BUILTIN_DEPENDENCIES = Array.from(
  new Set(
    NODE_BUILTIN_MODULE_NAMES.flatMap((name) => [name, `node:${name}`]),
  ),
).sort();
