import { describe, expect, it } from "vitest";
import {
  suggestRegistryDependenciesFromFiles,
  type RegistryCatalogEntry,
} from "./registry-dependency-suggestions";

const catalog: RegistryCatalogEntry[] = [
  {
    ownerLabel: "alice",
    name: "button",
    title: "Button",
    currentVersion: "1.0.0",
  },
  {
    ownerLabel: "bob",
    name: "input",
    title: "Input",
    currentVersion: "0.2.0",
  },
];

describe("suggestRegistryDependenciesFromFiles", () => {
  it("matches relative import to local file name against catalog", () => {
    const files = {
      "index.tsx": `import { Button } from "./Button";\nexport function Dialog() { return <Button />; }`,
      "Button.tsx": "export function Button() { return null; }",
    };
    const s = suggestRegistryDependenciesFromFiles(files, catalog);
    expect(s.some((x) => x.registryItem === "@alice/button")).toBe(true);
  });

  it("matches @owner/name import when in catalog", () => {
    const files = {
      "index.tsx": `import { Button } from "@alice/button";\nexport function X() { return <Button />; }`,
    };
    const s = suggestRegistryDependenciesFromFiles(files, catalog);
    expect(s).toHaveLength(1);
    expect(s[0].registryItem).toBe("@alice/button");
    expect(s[0].confidence).toBe("high");
  });

  it("includes stub-inferred ref when stub marker present", () => {
    const files = {
      "Dialog.tsx": `// auto-generated by cozy registry. do not edit.
export * from "./_deps/alice/button/index";`,
    };
    const s = suggestRegistryDependenciesFromFiles(files, catalog);
    expect(s.some((x) => x.registryItem === "@alice/button")).toBe(true);
  });
});
