import { describe, expect, it } from "vitest";
import { inferRegistryDependenciesFromStubScan } from "@cozy/registry-domain/registry-dependency-stub-scan";

describe("inferRegistryDependenciesFromStubScan", () => {
  it("infers @owner/name from cozy stub re-export paths", () => {
    const files = {
      "Button.tsx": `// auto-generated by cozy registry. do not edit.
export * from "./_deps/alice/ui-button/index";`,
    };
    expect(inferRegistryDependenciesFromStubScan(files)).toEqual(["@alice/ui-button"]);
  });

  it("returns empty when marker or _deps path missing", () => {
    expect(
      inferRegistryDependenciesFromStubScan({
        "x.tsx": 'export * from "./_deps/a/b/index";',
      }),
    ).toEqual([]);
    expect(
      inferRegistryDependenciesFromStubScan({
        "x.tsx": "// auto-generated by cozy registry\nexport const x = 1;",
      }),
    ).toEqual([]);
  });
});
