import { parseRegistryDependencyRef } from "@cozy/registry-domain/registry-graph";

const STUB_MARKER = "auto-generated by cozy registry";

/**
 * Best-effort inference of registry refs from Cozy stub files (spec §3.5.2).
 * Looks for `_deps/<owner>/<name>/` path segments in file contents.
 */
export function inferRegistryDependenciesFromStubScan(
  files: Record<string, string>,
): string[] {
  const out = new Set<string>();
  const re = /_deps\/([^/\s"']+)\/([^/\s"']+)\//g;
  for (const source of Object.values(files)) {
    if (!source.includes("_deps/")) continue;
    if (!source.includes(STUB_MARKER)) continue;
    let m: RegExpExecArray | null;
    const s = source;
    while ((m = re.exec(s)) !== null) {
      const ref = `@${m[1]}/${m[2]}`;
      if (parseRegistryDependencyRef(ref)) out.add(ref);
    }
  }
  return Array.from(out);
}
